/*
 * This file was automatically generated by EvoSuite
 * Thu Nov 11 06:26:17 GMT 2021
 */


import org.junit.Test;
import static org.junit.Assert.*;
// import org.evosuite.runtime.EvoRunner;
// import org.evosuite.runtime.EvoRunnerParameters;
// import org.junit.runner.RunWith;

// @RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
// public class Day_ESTest extends Day_ESTest_scaffolding {
public class Day_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      int int0 = Day.day(521, (-1448), (-1448));
      assertEquals(521, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      int int0 = Day.day(0, 655, 1);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      int int0 = Day.day(12, 12, 0);
      assertEquals(347, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      int int0 = Day.day((-877), 11, 31);
      assertEquals((-573), int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      int int0 = Day.day(1275, 10, 1275);
      assertEquals(1548, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      int int0 = Day.day(9, 9, (-15));
      assertEquals(252, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      int int0 = Day.day(8, 8, 8);
      assertEquals(221, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      int int0 = Day.day(1199, 7, 1548);
      assertEquals(1381, int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      int int0 = Day.day(151, 6, (-70));
      assertEquals(302, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      int int0 = Day.day((-1671), 5, (-15));
      assertEquals((-1551), int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      int int0 = Day.day(626, 4, 626);
      assertEquals(716, int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      int int0 = Day.day(2126, 3, 243);
      assertEquals(2185, int0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      int int0 = Day.day(0, 2, 100);
      assertEquals(31, int0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      int int0 = Day.day((-1259), 1, 0);
      assertEquals((-1259), int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Day day0 = new Day();
  }
}
