/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 24 05:05:46 GMT 2021
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

public class Simulator_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Simulator simulator0 = new Simulator();
      int int0 = simulator0.padBits((-1), (-22));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Simulator simulator0 = new Simulator();
      int int0 = simulator0.padBits((-8), (-8));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Simulator simulator0 = new Simulator();
      int int0 = simulator0.padBits(54000000, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Simulator simulator0 = new Simulator();
      int int0 = simulator0.padBits(48000000, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Simulator simulator0 = new Simulator();
      int int0 = simulator0.padBits(36000000, 6000000);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Simulator simulator0 = new Simulator();
      int int0 = simulator0.padBits(24000000, 1310);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Simulator simulator0 = new Simulator();
      int int0 = simulator0.padBits(12000000, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Simulator simulator0 = new Simulator();
      int int0 = simulator0.padBits(9000000, 9000000);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Simulator simulator0 = new Simulator();
      int int0 = simulator0.padBits(18000000, 18000000);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      Simulator simulator0 = new Simulator();
      int int0 = simulator0.padBits(6000000, 18000000);
      assertEquals(0, int0);
  }
}
