/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 15 12:22:39 CST 2018
 */


import static org.junit.Assert.assertEquals;

import org.junit.Test;

public class ProfitTest {

 @Test(timeout = 2000)
  public void test00()  throws Throwable  {
      Profit profit0 = new Profit();
      double double0 = profit0.func(600000.9099346637);
      assertEquals(33500.01364901996, double0, 0.01);
  }

  @Test(timeout = 2000)
  public void test01()  throws Throwable  {
      Profit profit0 = new Profit();
      double double0 = profit0.func(1000000.9691878615);
      assertEquals(39500.009691878615, double0, 0.01);
  }

  @Test(timeout = 2000)
  public void test02()  throws Throwable  {
      Profit profit0 = new Profit();
      double double0 = profit0.func(200001.0);
      assertEquals(17500.05, double0, 0.01);
  }

}
