/*
 * This file was automatically generated by EvoSuite
 * Wed Dec 29 20:49:49 GMT 2021
 */

import java.util.Arrays;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

public class Defroster_ESTest {
  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Defroster defroster0 = new Defroster();
      int[] intArray0 = defroster0.defroster();
      String answerArray = "[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 32767, 0, 0, 0, 0, 0, 0, 0, 0]";
      assertEquals(Arrays.toString(intArray0), answerArray);
  }
}
