/*
 * This file was automatically generated by EvoSuite
 * Thu Nov 11 06:40:38 GMT 2021
 */


import org.junit.Test;
import static org.junit.Assert.*;
// import org.evosuite.runtime.EvoRunner;
// import org.evosuite.runtime.EvoRunnerParameters;
// import org.junit.runner.RunWith;

// @RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
// public class Insert_ESTest extends Insert_ESTest_scaffolding {
public class Insert_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int[] intArray0 = Insert.insert(6);
      assertArrayEquals(new int[] {(-14), 6, 6, 28}, intArray0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int[] intArray0 = Insert.insert(28);
      assertArrayEquals(new int[] {(-14), 6, 28, 28}, intArray0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int[] intArray0 = Insert.insert(3309);
      assertArrayEquals(new int[] {(-14), 6, 28, 3309}, intArray0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Insert insert0 = new Insert();
  }
}
