/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 22 10:23:34 GMT 2021
 */


import org.junit.Test;
import static org.junit.Assert.*;
// import static org.evosuite.runtime.EvoAssertions.*;
// import org.evosuite.runtime.EvoRunner;
// import org.evosuite.runtime.EvoRunnerParameters;
// import org.junit.runner.RunWith;

// @RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
// public class Bisect_ESTest extends Bisect_ESTest_scaffolding {
public class Bisect_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      double double0 = Bisect.sqrt(1148.77536159);
      assertEquals(33.89366764764853, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      double double0 = Bisect.sqrt(1581.315092344);
      assertEquals(39.765778355858195, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      double double0 = Bisect.sqrt(0.16);
      assertEquals(0.4, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Bisect bisect0 = new Bisect();
  }
}
